const {Router} = require("express")
const usersController = require("../controllers/usersController")
const router = Router()
const registerValidations = require("../validations/registerValidations")
const editarPersonalinformationValidations = require("../validations/editarPersonalInformationValidations")
const editarPasswordValidations = require("../validations/editarPasswordValidations")
const editarShipmentInformationValidations = require("../validations/editarShipmentInformationValidations")
const authMiddleware = require("../middlewares/authMiddleware")
const guestMiddleware = require("../middlewares/guestMiddleware")
const adminMiddleware = require("../middlewares/adminMiddleware")

router.get("/registro", guestMiddleware, usersController.registro)
router.post("/registro", guestMiddleware, registerValidations, usersController.registroProcess)
router.get("/ingresar", guestMiddleware, usersController.ingresar)
router.post("/ingresar", guestMiddleware, usersController.ingresarProcess)
router.get("/perfil", authMiddleware, usersController.profile)
router.get("/perfil/editar-informacion-personal", authMiddleware, usersController.editProfilePersonalInformation)
router.put("/perfil/editar-informacion-personal/:userId", authMiddleware, editarPersonalinformationValidations, usersController.editProfilePersonalInformationProcess)
router.get("/perfil/editar-contrasena", authMiddleware, usersController.editPassword)
router.put("/perfil/editar-contrasena/:userId", authMiddleware, editarPasswordValidations, usersController.editPasswordProcess)
router.get("/perfil/edital-informacion-de-envio", authMiddleware, usersController.editShipment)
router.put("/perfil/editar-informacion-de-envio/:userId", authMiddleware, editarShipmentInformationValidations, usersController.editShipmentProcess)
router.get("/logout", authMiddleware, usersController.logout)
router.get("/ordenes", authMiddleware, usersController.ordenes)
router.post("/ordenes/editar-orden/:orderId/:newStatus", authMiddleware, adminMiddleware, usersController.editOrderStatus)

module.exports = router